import { type NextPage } from "next";
import Head from "next/head";
import PropertyCard from "../components/PropertyCard";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const properties = trpc.property.getAllProperties.useQuery();

  return (
    <>
      <Head>
        <title>Paseo 360</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" ">
        <h1>PASEO 360</h1>
        {!properties.isLoading &&
          properties?.data?.map((property) => (
            <PropertyCard key={property.id} property={property} />
          ))}
      </main>
    </>
  );
};

export default Home;
