import { type NextPage } from "next";
import Head from "next/head";
import MapContainer from "../components/MapContainer/MapContainer";
import PropertyCard from "../components/PropertyCard";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const properties = trpc.property.getAllProperties.useQuery();

  const createProperty = trpc.property.propertyCreate.useMutation();
  const createPropertyType = trpc.propertyType.propertyTypeCreate.useMutation();

  const handleClick = () => {
    createProperty.mutate({
      location: { lat: -31.521206732841065, lng: -68.5236785671953 },
      ambiences: 4,
      bathrooms: 1,
      address: "Concepción 234 oeste",
      typeId: "clby23yd40000e7ikw3evgekx",
      operation: "rent",
      price: 4000000,
    });
  };

  return (
    <>
      <Head>
        <title>Paseo 360</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" ">
        <section className="grid grid-cols-10 gap-x-4">
          <div className="col-span-4 ">
            <MapContainer />
          </div>
          <div className="col-span-6 grid grid-cols-2 gap-6">
            {!properties.isLoading &&
              properties?.data?.map((property) => (
                <PropertyCard key={property.id} property={property} />
              ))}
          </div>
        </section>
        <button onClick={handleClick}>CREAR PROPIEDAD</button>
      </main>
    </>
  );
};

export default Home;
